[package]
name = "wghttp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = { path = "../core" }
utoipa = "3"
tokio = { version = "1" , features = ["full"]}
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
ipnet = "2.7"
