[package]
name = "wghttp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core = {  path = "../core" }
if_mng_libc = { path = "../if_mng_libc" }
