name: build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true
            
      - name: build x86_64 linux
        run: |
          cargo build --release --target=x86_64-unknown-linux-gnu
          mv -v target/release/wghttp target/release/wghttp-x86_64-linux
          tar -czvf wghttp-x86_64-linux.tar.gz target/release/wghttp-x86_64-linux
      
      - name: github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "wghttp-*.tar.gz"
