name: release

on:
  workflow_dispatch:
    inputs:
      level:
        description: "release sem-level [-p|-m|-M]"
        required: true
        default: "-p"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: git config
        run: |
          git config --global user.name 'Baris Yuksel'
          git config --global user.email 'brsyuksel@users.noreply.github.com'

      - name: install semver script
        run: |
          wget https://raw.githubusercontent.com/fmahnke/shell-semver/master/increment_version.sh
          chmod +x ./increment_version.sh
      
      - name: install toml-cli
        run: |
          wget https://github.com/gnprice/toml-cli/releases/download/v0.2.3/toml-0.2.3-x86_64-linux.tar.gz
          tar zxvf toml-0.2.3-x86_64-linux.tar.gz
      
      - name: get current version
        run: |
          echo "CURRENT_VERSION=$(./toml-0.2.3-x86_64-linux/toml get wghttp/Cargo.toml package.version --raw)" >> $GITHUB_ENV
      
      - name: bump version
        run: |
          echo "NEXT_VERSION=$(./increment_version.sh $RELEASE_LEVEL $CURRENT_VERSION)" >> $GITHUB_ENV
        env:
          RELEASE_LEVEL: ${{ inputs.level }}
      
      - name: set tag version
        run: |
          echo "TAG_VERSION=v${NEXT_VERSION}" >> $GITHUB_ENV

      - name: update wghttp/Cargo.toml
        run: |
          ./toml-0.2.3-x86_64-linux/toml set wghttp/Cargo.toml package.version $NEXT_VERSION > wghttp/Cargo.toml.new
          mv -v wghttp/Cargo.toml.new wghttp/Cargo.toml
      
      - name: commit and push
        run: |
          rm -Rfv toml-0.2.3-x86_64-linux*
          git add wghttp/Cargo.toml
          git commit -m "bump version"
          git push
          git tag $TAG_VERSION
          git push --tags

      - name: install rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true
            
      - name: build x86_64 linux
        run: |
          cargo build --release --target=x86_64-unknown-linux-gnu
          mkdir -v bin
          mv -v target/x86_64-unknown-linux-gnu/release/wghttp ./bin/wghttp
          tar -czvf wghttp-x86_64-linux.tar.gz ./bin/wghttp
      
      - name: github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "wghttp-*.tar.gz"
          tag: ${{ env.TAG_VERSION }}
