name: release

on:
  workflow_dispatch:
    inputs:
      level:
        description: "release sem-level [patch|minor|major]"
        required: true
        default: "patch"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: install rust toolchain
        uses: actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          override: true
      
      - name: install cargo release
        run: |
          cargo install cargo-release

      - name: release
        run: |
          cargo release --package wghttp --no-publish --tag-prefix "" --no-confirm --execute $RELEASE_LEVEL
        env:
          RELEASE_LEVEL: ${{ inputs.level }}
